/* Autogenerated file.  Manual modification is pointless. */

#include "sns_rc.h"
#include "sns_register.h"
#include "sns_types.h"

sns_rc sns_register_suid_sensor(sns_register_cb const *register_api);
sns_rc sns_register_cm(sns_register_cb const *register_api);
sns_rc sns_register_diag_sensor(sns_register_cb const *register_api);
sns_rc sns_register_dynamic_sensor(sns_register_cb const *register_api);
sns_rc sns_register_power_sensor(sns_register_cb const *register_api);
sns_rc sns_accel_cal_register(sns_register_cb const *register_api);
sns_rc sns_register_ak0991x(sns_register_cb const *register_api);
sns_rc sns_amd_register(sns_register_cb const *register_api);
sns_rc sns_async_com_port_register(sns_register_cb const *register_api);
sns_rc sns_basic_gestures_register(sns_register_cb const *register_api);
sns_rc sns_register_bmp285(sns_register_cb const *register_api);
sns_rc sns_register_spl06(sns_register_cb const *register_api);
sns_rc sns_bring_to_ear_register(sns_register_cb const *register_api);
sns_rc sns_register_bu52053nvx(sns_register_cb const *register_api);
sns_rc sns_ccd_register(sns_register_cb const *register_api);
sns_rc sns_cmc_register(sns_register_cb const *register_api);
sns_rc sns_register_dae_sensor(sns_register_cb const *register_api);
sns_rc sns_device_orient_register(sns_register_cb const *register_api);
sns_rc sns_distance_bound_register(sns_register_cb const *register_api);
sns_rc sns_dpc_register(sns_register_cb const *register_api);
sns_rc sns_da_test_register(sns_register_cb const *register_api);
sns_rc sns_ext_svc_register(sns_register_cb const *register_api);
sns_rc sns_facing_register(sns_register_cb const *register_api);
sns_rc sns_fmv_register(sns_register_cb const *register_api);
sns_rc sns_game_rv_register(sns_register_cb const *register_api);
sns_rc sns_geomag_rv_register(sns_register_cb const *register_api);
sns_rc sns_gravity_register(sns_register_cb const *register_api);
sns_rc sns_gyro_cal_register(sns_register_cb const *register_api);
sns_rc sns_gyro_rot_matrix_register(sns_register_cb const *register_api);
sns_rc sns_register_interrupt(sns_register_cb const *register_api);
sns_rc sns_register_lsm6ds3(sns_register_cb const *register_api);
sns_rc sns_register_lsm6dsm(sns_register_cb const *register_api);
sns_rc sns_mag_cal_register(sns_register_cb const *register_api);
sns_rc sns_oem1_register(sns_register_cb const *register_api);
sns_rc sns_pedometer_register(sns_register_cb const *register_api);
sns_rc sns_psmd_register(sns_register_cb const *register_api);
sns_rc sns_register_registry_sensor(sns_register_cb const *register_api);
sns_rc sns_remote_proc_state_register(sns_register_cb const *register_api);
sns_rc sns_resampler_register(sns_register_cb const *register_api);
sns_rc sns_rmd_register(sns_register_cb const *register_api);
sns_rc sns_rotv_register(sns_register_cb const *register_api);
sns_rc sns_register_shtw2(sns_register_cb const *register_api);
sns_rc sns_signal_register(sns_register_cb const *register_api);
sns_rc sns_smd_register(sns_register_cb const *register_api);
sns_rc sns_multishake_register(sns_register_cb const *register_api);
sns_rc sns_test_register(sns_register_cb const *register_api);
sns_rc sns_tilt_register(sns_register_cb const *register_api);
sns_rc sns_timer_register(sns_register_cb const *register_api);
sns_rc sns_register_ams(sns_register_cb const *register_api);

const sns_register_entry sns_register_sensor_list[] =
{
 { sns_register_suid_sensor, 1},
 { sns_register_cm, 1},
 { sns_register_diag_sensor, 1},
 { sns_register_dynamic_sensor, 1},
 { sns_register_power_sensor, 1},
 { sns_accel_cal_register, 1},
 { sns_register_ak0991x, 1},
 { sns_amd_register, 1},
 { sns_async_com_port_register, 1},
 { sns_basic_gestures_register, 1},
 { sns_register_bmp285, 1},
 { sns_register_spl06, 1},
 { sns_bring_to_ear_register, 1},
 { sns_register_bu52053nvx, 1},
 { sns_ccd_register, 1},
 { sns_cmc_register, 1},
 { sns_register_dae_sensor, 1},
 { sns_device_orient_register, 1},
 { sns_distance_bound_register, 1},
 { sns_dpc_register, 1},
 { sns_da_test_register, 1},
 { sns_ext_svc_register, 1},
 { sns_facing_register, 1},
 { sns_fmv_register, 1},
 { sns_game_rv_register, 1},
 { sns_geomag_rv_register, 1},
 { sns_gravity_register, 1},
 { sns_gyro_cal_register, 1},
 { sns_gyro_rot_matrix_register, 1},
 { sns_register_interrupt, 1},
 { sns_register_lsm6ds3, 1},
 { sns_register_lsm6dsm, 1},
 { sns_mag_cal_register, 1},
 { sns_oem1_register, 1},
 { sns_pedometer_register, 1},
 { sns_psmd_register, 1},
 { sns_register_registry_sensor, 1},
 { sns_remote_proc_state_register, 1},
 { sns_resampler_register, 1},
 { sns_rmd_register, 1},
 { sns_rotv_register, 1},
 { sns_register_shtw2, 1},
 { sns_signal_register, 1},
 { sns_smd_register, 1},
 { sns_multishake_register, 1},
 { sns_test_register, 1},
 { sns_tilt_register, 1},
 { sns_timer_register, 1},
 { sns_register_ams, 1},
};

const uint32_t sns_register_sensor_list_len = ARR_SIZE(sns_register_sensor_list);

